export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const SET_USER = 'SET_USER';

// Notifications types
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const SET_ANIMATION = 'SET_ANIMATION';

// Tasks types
export const GET_TASKS_START = 'GET_TASKS_START';
export const GET_TASKS_FINISH = 'GET_TASKS_FINISH';
export const GET_TASKS_ERROR = 'GET_TASKS_ERROR';

export const ADD_TASK_START = 'ADD_TASK_START';
export const ADD_TASK_FINISH = 'ADD_TASK_FINISH';
export const ADD_TASK_ERROR = 'ADD_TASK_ERROR';

export const RESET_TASK_ERRORS = 'RESET_TASK_ERRORS';

export const DELETE_TASK_START = 'DELETE_TASK_START';
export const DELETE_TASK_FINISH = 'DELETE_TASK_FINISH';
export const DELETE_TASK_ERROR = 'DELETE_TASK_ERROR';
